version: '3.8'

services:
  php:
    image: ngyuki/php-dev:8.0
    depends_on:
      - mysql
    volumes:
      - .:/work
    working_dir: /work
    environment: &environment
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  mysql:
    image: mysql:8
    environment: *environment
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
